### ISSUE TITLE
解包索尼电视固件的img时候崩溃

### ISSUE THREAD

**Issue by ohyeah521** [AEnjoy/unpackandroidrom#5]
索尼固件下载地址：https://service.sony.com.cn/download/firm/00003035.html

最后一步解包img的时候直接崩溃了

**Comment by AEnjoy** [comment]
Received

**Comment by ohyeah521** [comment]
有什么进展吗？

**Comment by AEnjoy** [comment]
第一步 解压zip里的那个zip，然后用脚本解压出解包出来的zip
第二步 打开运行路径下的output文件夹，使用7-zip打开
![image](https://github.com/AEnjoy/unpackandroidrom/assets/37976919/e05ee89c-7ec1-4a9e-9b41-e9bcaee8df89)
![image](https://github.com/AEnjoy/unpackandroidrom/assets/37976919/d2b41a95-7749-4a55-8bb5-659d8112ea74)
继续双击这个system.img
![image](https://github.com/AEnjoy/unpackandroidrom/assets/37976919/56f2f4b5-87dd-4c20-8d04-061bdc09e4f7)
如果你还需要解压system分区,用7z解压就行

**Comment by ohyeah521** [comment]
@AEnjoy   我这里无法用7z打开system.img文件。

索尼固件sony_dtv0FA80A0CA0AC_00004600_16074801000852.zip   MD5: 730681D08B4C770FECCE49EE7F927C47

程序提取的system.img  MD5: BA96484C09194FB36CA257C2BCB30E31



sony_dtv0FA80A0CA0AC_00004600_16074801000852.zip 文件内容：
<img width="962" alt="1" src="https://github.com/AEnjoy/unpackandroidrom/assets/1449374/de152104-8d3a-463b-9aff-3770ded7728a">

运行程序提取img，解包img如果输入y就闪退了
<img width="734" alt="2" src="https://github.com/AEnjoy/unpackandroidrom/assets/1449374/17462b3d-5aad-458b-950e-6d4e9f12efe9">


用7z打开img文件提示出错：
<img width="631" alt="2024-07-07_225817" src="https://github.com/AEnjoy/unpackandroidrom/assets/1449374/0da09a65-3149-4e20-9b74-aa6928c8f687">

<img width="343" alt="4" src="https://github.com/AEnjoy/unpackandroidrom/assets/1449374/3ca0c27c-8db2-43f7-99c0-87f0ef884126">

**Comment by AEnjoy** [comment]
试试把7z更到最新 我这边是能用7z打开的

**Comment by ohyeah521** [comment]
@AEnjoy 谢谢，果然时7z升级到最新就可以了。
